# Generated by Django 2.2 on 2019-09-16 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_bas_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop', models.CharField(max_length=10, verbose_name='车间')),
                ('worksection', models.CharField(max_length=10, verbose_name='工段')),
                ('team', models.CharField(max_length=10, verbose_name='班组')),
                ('level', models.CharField(max_length=10, verbose_name='层级')),
                ('shift', models.CharField(max_length=5, verbose_name='班次')),
                ('uloc', models.CharField(max_length=20, verbose_name='工位')),
                ('date', models.DateField(verbose_name='日期')),
                ('title', models.CharField(max_length=300, verbose_name='检查项')),
                ('res', models.CharField(max_length=5, verbose_name='检查结果')),
                ('reason', models.CharField(max_length=100, verbose_name='检查项')),
                ('res_time', models.DateField(verbose_name='检查日期')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('name', models.CharField(max_length=10, verbose_name='名字')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
