# Generated by Django 2.2 on 2019-09-16 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='reason',
            field=models.CharField(max_length=100, verbose_name='原因'),
        ),
    ]
