# Generated by Django 2.2 on 2019-09-16 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20190916_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='bas_title',
            name='status',
            field=models.CharField(default='0', max_length=5, verbose_name='检查状态'),
        ),
    ]
