# Generated by Django 2.2 on 2019-10-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_bas_title_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='zzuser',
            name='is_admin',
            field=models.CharField(max_length=5, null=True, verbose_name='是否管理员'),
        ),
    ]
