# Generated by Django 2.2 on 2019-10-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_zzuser_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='app_vesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appvesion', models.CharField(max_length=20, verbose_name='版本号')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
