# Generated by Django 2.2 on 2019-11-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_app_vesion'),
    ]

    operations = [
        migrations.CreateModel(
            name='pc_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop', models.CharField(max_length=10, verbose_name='车间')),
                ('worksection', models.CharField(max_length=10, verbose_name='工段')),
                ('team', models.CharField(max_length=10, verbose_name='班组')),
                ('level', models.CharField(max_length=10, verbose_name='层级')),
                ('shift', models.CharField(max_length=5, verbose_name='班次')),
                ('uloc', models.CharField(max_length=20, verbose_name='工位')),
                ('date', models.DateField(verbose_name='日期')),
                ('status', models.CharField(default='0', max_length=5, verbose_name='检查状态')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='bas_title',
            name='date',
        ),
    ]
