# Generated by Django 2.2 on 2019-11-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_auto_20191105_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='plan_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=20, verbose_name='点检项目id')),
                ('uloc', models.CharField(max_length=20, verbose_name='工位')),
                ('date', models.DateField(verbose_name='日期')),
                ('status', models.CharField(default='0', max_length=5, verbose_name='检查状态')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
