# Generated by Django 2.2 on 2019-11-05 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_plan_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='plan_status',
        ),
    ]
