# Generated by Django 2.2 on 2019-11-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_problem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem_status',
            name='date',
            field=models.DateField(verbose_name='计划日期'),
        ),
    ]
