# Generated by Django 2.2 on 2019-12-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_auto_20191129_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem_status',
            name='refuse_time',
            field=models.DateTimeField(null=True, verbose_name='驳回时间'),
        ),
        migrations.AlterField(
            model_name='problem_status',
            name='updatetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
