# Generated by Django 2.2 on 2019-12-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_auto_20191203_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem_status',
            name='actual_close_date',
            field=models.DateTimeField(null=True, verbose_name='实际关闭日期'),
        ),
    ]
